theme: jekyll-theme-minimal
author_profile: true
title: WEB322
description: Web Programming Tools and Frameworks
encoding: UTF-8
url: https://patrick-crawford.github.io/WEB322-Backup
baseurl: /WEB322-Backup
